from os import path
ROOT_DIR = path.dirname(__file__)
ASSET_DIR = path.join(ROOT_DIR, 'assets')
WALL_APPLIANCE_PATH = path.join(ASSET_DIR, "Wall Appliances")
COOKTOP_APPLIANCE_PATH = path.join(ASSET_DIR, "Cooktops")
SINK_APPLIANCE_PATH = path.join(ASSET_DIR, "Sinks")
FAUCET_APPLIANCE_PATH = path.join(ASSET_DIR, "Faucets")
LAUNDRY_APPLIANCE_PATH = path.join(ASSET_DIR, "Laundry")
MATERIAL_FILE = path.join(ASSET_DIR, "materials", "materials.blend")
COUNTERTOP_PARTS_DIR = path.join(ASSET_DIR, "Countertop Parts")
BACKSPLASH_PART = path.join(COUNTERTOP_PARTS_DIR, "Backsplash.blend")
CTOP = path.join(COUNTERTOP_PARTS_DIR, "Straight Countertop Square.blend")
NOTCHED_CTOP = path.join(COUNTERTOP_PARTS_DIR, "Corner Notched Countertop Square.blend")
DIAGONAL_CTOP = path.join(COUNTERTOP_PARTS_DIR, "Corner Diagonal Countertop Square.blend")